package com.dottstudio.controller;

import com.dottstudio.util.DBConnection;
import java.io.IOException;
import java.io.PrintWriter;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.SQLException;
import java.sql.Statement;
import jakarta.servlet.ServletException;
import jakarta.servlet.annotation.WebServlet;
import jakarta.servlet.http.HttpServlet;
import jakarta.servlet.http.HttpServletRequest;
import jakarta.servlet.http.HttpServletResponse;

@WebServlet("/api/setup-db")
public class SetupServlet extends HttpServlet {
    private static final long serialVersionUID = 1L;

    protected void doGet(HttpServletRequest request, HttpServletResponse response)
            throws ServletException, IOException {
        response.setContentType("text/plain");
        PrintWriter out = response.getWriter();
        out.println("Running Database Setup...");

        try (Connection conn = DBConnection.getConnection()) {

            // 2. FORCE Recreate 'designers' table (Fixing missing ID column)
            try {
                executeSQL(conn, "DROP TABLE designers CASCADE CONSTRAINTS");
                out.println("Dropped existing DESIGNERS table.");
            } catch (SQLException e) {
                out.println("No existing DESIGNERS table to drop.");
            }

            out.println("Creating DESIGNERS table...");
            String designersSql = "CREATE TABLE designers (" +
                    "id NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY PRIMARY KEY, " +
                    "user_id NUMBER NOT NULL, " +
                    "specialty VARCHAR2(100), " +
                    "availability VARCHAR2(255), " +
                    "CONSTRAINT fk_designer_user FOREIGN KEY (user_id) REFERENCES users(id))";
            executeSQL(conn, designersSql);
            out.println("DESIGNERS table created successfully.");

            // 3. FORCE Recreate 'bookings' table
            try {
                executeSQL(conn, "DROP TABLE bookings CASCADE CONSTRAINTS");
                out.println("Dropped existing BOOKINGS table.");
            } catch (SQLException e) {
                out.println("No existing BOOKINGS table to drop (" + e.getMessage() + ")");
            }

            out.println("Creating BOOKINGS table...");
            String bookingSql = "CREATE TABLE bookings (" +
                    "id NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY PRIMARY KEY, " +
                    "client_name VARCHAR2(255), " +
                    "client_email VARCHAR2(255), " +
                    "client_phone VARCHAR2(50), " +
                    "designer_name VARCHAR2(255), " +
                    "designer_id NUMBER, " +
                    "booking_date VARCHAR2(50), " +
                    "booking_time VARCHAR2(50), " +
                    "notes VARCHAR2(1000), " +
                    "status VARCHAR2(50) DEFAULT 'Confirmed', " +
                    "created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP" +
                    ")";
            executeSQL(conn, bookingSql);
            out.println("BOOKINGS table created successfully.");

        } catch (SQLException e) {
            e.printStackTrace();
            out.println("ERROR: " + e.getMessage());
            e.printStackTrace(out);
        }
    }

    private void executeSQL(Connection conn, String sql) throws SQLException {
        try (Statement stmt = conn.createStatement()) {
            stmt.execute(sql);
        }
    }
}
