package com.dottstudio.util;

import java.sql.*;

public class DatabaseSetupNormalized {

    public static void main(String[] args) {
        System.out.println(">>> CREATING NORMALIZED DATABASE SCHEMA (Version 2: Bookings-Designers Bridge)...");
        try (Connection conn = DBConnection.getConnection()) {

            // Drop existing tables
            dropTables(conn);

            // 1. Lookup Tables
            createRolesTable(conn);
            createReferralsTable(conn);

            // 2. Core Hierarchy (Inheritance)
            createUsersTable(conn);
            createStaffTable(conn);
            createDesignersTable(conn); // Includes Specialty column
            createAdminsTable(conn);

            // 3. Business Tables
            createBookingsTable(conn); // No DesignerID here

            // 4. Bridge Table
            createBookingDesignersTable(conn); // Connects Bookings <-> Designers

            // 5. Seed Data
            seedData(conn);

            System.out.println(">>> SCHEMA CREATION COMPLETED SUCCESSFULLY!");

        } catch (SQLException e) {
            System.err.println(">>> ERROR DURING SCHEMA CREATION:");
            e.printStackTrace();
        }
    }

    private static void dropTables(Connection conn) throws SQLException {
        System.out.println(">>> Dropping existing tables...");
        String[] tables = {
                "BOOKING_DESIGNERS", "BOOKINGS",
                "DESIGNER_SPECIALTIES", "SPECIALTIES", // Cleanup old bridge
                "DESIGNERS", "ADMINS", "STAFF",
                "USERS", "ROLES", "REFERRALS"
        };

        for (String table : tables) {
            try {
                executeSQL(conn, "DROP TABLE " + table + " CASCADE CONSTRAINTS");
                System.out.println("    Dropped: " + table);
            } catch (SQLException e) {
                // Print error to understand why drop failed
                System.out.println("    Failed to drop " + table + ": " + e.getMessage());
            }
        }
    }

    private static void createRolesTable(Connection conn) throws SQLException {
        System.out.println(">>> Creating ROLES table...");
        String sql = "CREATE TABLE ROLES (" +
                "RoleID NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY PRIMARY KEY, " +
                "RoleName VARCHAR2(50) NOT NULL UNIQUE)";
        executeSQL(conn, sql);
    }

    private static void createReferralsTable(Connection conn) throws SQLException {
        System.out.println(">>> Creating REFERRALS table...");
        String sql = "CREATE TABLE REFERRALS (" +
                "ReferralID NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY PRIMARY KEY, " +
                "ReferralSource VARCHAR2(100) NOT NULL UNIQUE)";
        executeSQL(conn, sql);
    }

    private static void createUsersTable(Connection conn) throws SQLException {
        System.out.println(">>> Creating USERS table...");
        String sql = "CREATE TABLE USERS (" +
                "UserID NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY PRIMARY KEY, " +
                "Email VARCHAR2(100) NOT NULL UNIQUE, " +
                "PasswordHash VARCHAR2(255) NOT NULL, " +
                "FirstName VARCHAR2(50) NOT NULL, " +
                "LastName VARCHAR2(50) NOT NULL, " +
                "Phone VARCHAR2(20), " +
                "Address VARCHAR2(255), " +
                "RoleID NUMBER NOT NULL, " +
                "ReferralID NUMBER, " +
                "ReferredByUserID NUMBER, " +
                "CreatedAt TIMESTAMP DEFAULT CURRENT_TIMESTAMP, " +
                "CONSTRAINT FK_Users_Roles FOREIGN KEY (RoleID) REFERENCES ROLES(RoleID), " +
                "CONSTRAINT FK_Users_Referrals FOREIGN KEY (ReferralID) REFERENCES REFERRALS(ReferralID), " +
                "CONSTRAINT FK_Users_ReferredBy FOREIGN KEY (ReferredByUserID) REFERENCES USERS(UserID))";
        executeSQL(conn, sql);
    }

    private static void createStaffTable(Connection conn) throws SQLException {
        System.out.println(">>> Creating STAFF table...");
        String sql = "CREATE TABLE STAFF (" +
                "StaffID NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY PRIMARY KEY, " +
                "UserID NUMBER NOT NULL UNIQUE, " +
                "ManagerID NUMBER, " +
                "Position VARCHAR2(50), " +
                "JoinDate DATE DEFAULT CURRENT_DATE, " +
                "CONSTRAINT FK_Staff_User FOREIGN KEY (UserID) REFERENCES USERS(UserID) ON DELETE CASCADE, " +
                "CONSTRAINT FK_Staff_Manager FOREIGN KEY (ManagerID) REFERENCES STAFF(StaffID))";
        executeSQL(conn, sql);
    }

    private static void createDesignersTable(Connection conn) throws SQLException {
        System.out.println(">>> Creating DESIGNERS table...");
        String sql = "CREATE TABLE DESIGNERS (" +
                "DesignerID NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY PRIMARY KEY, " +
                "StaffID NUMBER NOT NULL UNIQUE, " +
                "HourlyRate NUMBER(10, 2), " +
                "Bio CLOB, " +
                "Availability VARCHAR2(255), " +
                "Specialty VARCHAR2(100), " + // Moved back here
                "CONSTRAINT FK_Designer_Staff FOREIGN KEY (StaffID) REFERENCES STAFF(StaffID) ON DELETE CASCADE)";
        executeSQL(conn, sql);
    }

    private static void createAdminsTable(Connection conn) throws SQLException {
        System.out.println(">>> Creating ADMINS table...");
        String sql = "CREATE TABLE ADMINS (" +
                "AdminID NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY PRIMARY KEY, " +
                "StaffID NUMBER NOT NULL UNIQUE, " +
                "Department VARCHAR2(100), " +
                "CONSTRAINT FK_Admin_Staff FOREIGN KEY (StaffID) REFERENCES STAFF(StaffID) ON DELETE CASCADE)";
        executeSQL(conn, sql);
    }

    private static void createBookingsTable(Connection conn) throws SQLException {
        System.out.println(">>> Creating BOOKINGS table (Without DesignerID)...");
        String sql = "CREATE TABLE BOOKINGS (" +
                "BookingID NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY PRIMARY KEY, " +
                "CustomerID NUMBER NOT NULL, " +
                "BookingDate DATE NOT NULL, " +
                "BookingTime VARCHAR2(10) NOT NULL, " +
                "Status VARCHAR2(20) DEFAULT 'Pending', " +
                "Notes CLOB, " +
                "CreatedAt TIMESTAMP DEFAULT CURRENT_TIMESTAMP, " +
                "CONSTRAINT FK_Booking_Customer FOREIGN KEY (CustomerID) REFERENCES USERS(UserID))";
        executeSQL(conn, sql);
    }

    private static void createBookingDesignersTable(Connection conn) throws SQLException {
        System.out.println(">>> Creating BOOKING_DESIGNERS (Bridge) table...");
        String sql = "CREATE TABLE BOOKING_DESIGNERS (" +
                "BookingID NUMBER NOT NULL, " +
                "DesignerID NUMBER NOT NULL, " +
                "PRIMARY KEY (BookingID, DesignerID), " +
                "CONSTRAINT FK_BD_Booking FOREIGN KEY (BookingID) REFERENCES BOOKINGS(BookingID) ON DELETE CASCADE, " +
                "CONSTRAINT FK_BD_Designer FOREIGN KEY (DesignerID) REFERENCES DESIGNERS(DesignerID) ON DELETE CASCADE)";
        executeSQL(conn, sql);
    }

    private static void seedData(Connection conn) throws SQLException {
        System.out.println(">>> Seeding initial data...");

        // Roles
        executeSQL(conn, "INSERT INTO ROLES (RoleName) VALUES ('ADMIN')");
        executeSQL(conn, "INSERT INTO ROLES (RoleName) VALUES ('DESIGNER')");
        executeSQL(conn, "INSERT INTO ROLES (RoleName) VALUES ('CUSTOMER')");

        // Referrals
        String[] refs = { "friends", "social_media", "search_engine", "advertisement", "other" };
        for (String r : refs) {
            try {
                executeSQL(conn, "INSERT INTO REFERRALS (ReferralSource) VALUES ('" + r + "')");
            } catch (Exception e) {
            }
        }

        // Admin Creation
        createDefaultAdmin(conn);
        createDefaultDesigners(conn);
        createDefaultBookings(conn);
    }

    private static void createDefaultBookings(Connection conn) throws SQLException {
        // 1. Create a Default Customer
        String email = "jane@example.com";
        String passHash = "mIeWUM/hqNr2FShXO50eg0AXxwo82/JZzEFbPmV25DY="; // admin123
        int customerId = -1;

        try (PreparedStatement stmt = conn.prepareStatement(
                "INSERT INTO USERS (Email, PasswordHash, FirstName, LastName, RoleID) " +
                        "VALUES (?, ?, 'Jane', 'Doe', (SELECT RoleID FROM ROLES WHERE RoleName='CUSTOMER'))",
                new String[] { "UserID" })) {
            stmt.setString(1, email);
            stmt.setString(2, passHash);
            stmt.executeUpdate();
            ResultSet rs = stmt.getGeneratedKeys();
            if (rs.next())
                customerId = rs.getInt(1);
            System.out.println(">>> Created Customer: " + email);
        } catch (SQLException e) {
            System.out.println(">>> Customer might already exist, retrieving ID...");
            // Retrieve ID if exists (for re-runs if logic changes)
            try (PreparedStatement getStmt = conn.prepareStatement("SELECT UserID FROM USERS WHERE Email = ?")) {
                getStmt.setString(1, email);
                ResultSet rs = getStmt.executeQuery();
                if (rs.next())
                    customerId = rs.getInt(1);
            }
        }

        if (customerId != -1) {
            System.out.println(">>> Seeding Bookings...");
            // 2. Create Bookings (2026 dates)
            String[][] bookings = {
                    { "2026-02-15", "10:00", "Alice", "Full Home Renovation" },
                    { "2026-02-20", "14:00", "Bob", "Kitchen Remodel" }
            };

            for (String[] b : bookings) {
                try {
                    // Start Transaction-like block (simplified)

                    // A. Insert Booking
                    int bookingId = -1;
                    try (PreparedStatement stmt = conn.prepareStatement(
                            "INSERT INTO BOOKINGS (CustomerID, BookingDate, BookingTime, Status, Notes) " +
                                    "VALUES (?, TO_DATE(?, 'YYYY-MM-DD'), ?, 'Confirmed', ?)",
                            new String[] { "BookingID" })) {
                        stmt.setInt(1, customerId);
                        stmt.setString(2, b[0]);
                        stmt.setString(3, b[1]);
                        stmt.setString(4, b[3]);
                        stmt.executeUpdate();
                        ResultSet rs = stmt.getGeneratedKeys();
                        if (rs.next())
                            bookingId = rs.getInt(1);
                    }

                    // B. Link Designer (Find ID first)
                    if (bookingId != -1) {
                        try (PreparedStatement dStmt = conn.prepareStatement(
                                "SELECT DesignerID FROM DESIGNERS d JOIN STAFF s ON d.StaffID=s.StaffID JOIN USERS u ON s.UserID=u.UserID WHERE u.FirstName = ?")) {
                            dStmt.setString(1, b[2]);
                            ResultSet dRs = dStmt.executeQuery();
                            if (dRs.next()) {
                                int dId = dRs.getInt(1);
                                executeSQL(conn, "INSERT INTO BOOKING_DESIGNERS (BookingID, DesignerID) VALUES ("
                                        + bookingId + ", " + dId + ")");
                                System.out.println("    Created Booking for " + b[2] + " on " + b[0]);
                            }
                        }
                    }
                } catch (SQLException e) {
                    System.out.println("    Error seeding booking: " + e.getMessage());
                }
            }
        }
    }

    private static void createDefaultAdmin(Connection conn) throws SQLException {
        String email = "admin@dottstudio.com";
        // SHA-256 Hash of 'admin123' (Salt: DottStudioSalt)
        // Matches PasswordUtils logic used by LoginServlet
        String passHash = "mIeWUM/hqNr2FShXO50eg0AXxwo82/JZzEFbPmV25DY=";

        try (PreparedStatement stmt = conn.prepareStatement(
                "INSERT INTO USERS (Email, PasswordHash, FirstName, LastName, RoleID) " +
                        "VALUES (?, ?, 'System', 'Admin', (SELECT RoleID FROM ROLES WHERE RoleName='ADMIN'))",
                new String[] { "UserID" })) {

            stmt.setString(1, email);
            stmt.setString(2, passHash);
            stmt.executeUpdate();

            ResultSet rs = stmt.getGeneratedKeys();
            if (rs.next()) {
                int userId = rs.getInt(1);
                try (PreparedStatement sStmt = conn.prepareStatement(
                        "INSERT INTO STAFF (UserID, Position) VALUES (?, 'System Owner')",
                        new String[] { "StaffID" })) {
                    sStmt.setInt(1, userId);
                    sStmt.executeUpdate();

                    ResultSet sRs = sStmt.getGeneratedKeys();
                    if (sRs.next()) {
                        int staffId = sRs.getInt(1);
                        executeSQL(conn, "INSERT INTO ADMINS (StaffID, Department) VALUES (" + staffId + ", 'IT')");
                        System.out.println(">>> Created Admin: " + email);
                    }
                }
            }
        } catch (SQLException e) {
            System.out.println(">>> Admin might already exist.");
        }
    }

    private static void createDefaultDesigners(Connection conn) throws SQLException {
        String[][] designers = {
                { "alice@dottstudio.com", "Alice", "Johnson", "Modern Minimalist", "09:00,10:00,14:00" },
                { "bob@dottstudio.com", "Bob", "Smith", "Traditional Elegance", "11:00,15:00,16:00" },
                { "carol@dottstudio.com", "Carol", "Lee", "Contemporary Fusion", "08:00,12:00,17:00" }
        };

        String passHash = "mIeWUM/hqNr2FShXO50eg0AXxwo82/JZzEFbPmV25DY="; // all use admin123 for demo

        System.out.println(">>> Seeding Designers...");

        for (String[] d : designers) {
            try {
                // 1. User
                int userId = -1;
                try (PreparedStatement stmt = conn.prepareStatement(
                        "INSERT INTO USERS (Email, PasswordHash, FirstName, LastName, RoleID) " +
                                "VALUES (?, ?, ?, ?, (SELECT RoleID FROM ROLES WHERE RoleName='DESIGNER'))",
                        new String[] { "UserID" })) {
                    stmt.setString(1, d[0]);
                    stmt.setString(2, passHash);
                    stmt.setString(3, d[1]);
                    stmt.setString(4, d[2]);
                    stmt.executeUpdate();
                    ResultSet rs = stmt.getGeneratedKeys();
                    if (rs.next())
                        userId = rs.getInt(1);
                }

                if (userId != -1) {
                    // 2. Staff
                    int staffId = -1;
                    try (PreparedStatement stmt = conn.prepareStatement(
                            "INSERT INTO STAFF (UserID, Position) VALUES (?, 'Senior Designer')",
                            new String[] { "StaffID" })) {
                        stmt.setInt(1, userId);
                        stmt.executeUpdate();
                        ResultSet rs = stmt.getGeneratedKeys();
                        if (rs.next())
                            staffId = rs.getInt(1);
                    }

                    if (staffId != -1) {
                        // 3. Designer
                        try (PreparedStatement stmt = conn.prepareStatement(
                                "INSERT INTO DESIGNERS (StaffID, HourlyRate, Bio, Specialty, Availability) " +
                                        "VALUES (?, 150.00, 'Expert designer.', ?, ?)")) {
                            stmt.setInt(1, staffId);
                            stmt.setString(2, d[3]);
                            stmt.setString(3, d[4]);
                            stmt.executeUpdate();
                            System.out.println("    Created Designer: " + d[1] + " " + d[2]);
                        }
                    }
                }
            } catch (SQLException e) {
                System.out.println("    Skipping existing: " + d[0]);
            }
        }
    }

    private static void executeSQL(Connection conn, String sql) throws SQLException {
        try (Statement stmt = conn.createStatement()) {
            stmt.execute(sql);
        }
    }
}
