package com.dottstudio.util;

import java.sql.Connection;
import java.sql.DatabaseMetaData;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;

public class DatabaseSetup {

    public static void main(String[] args) {
        System.out.println(">>> SETTING UP FINAL NORMALIZED SCHEMA...");
        try (Connection conn = DBConnection.getConnection()) {

            // 1. CLEANUP (Drop in order)
            dropTable(conn, "DESIGNER_SCHEDULE"); // New table
            dropTable(conn, "BOOKING_CATEGORIES");
            dropTable(conn, "BOOKINGS");
            dropTable(conn, "DESIGNER_SPECIALTIES");
            dropTable(conn, "DESIGNERS");
            dropTable(conn, "STAFF");
            dropTable(conn, "USERS");
            dropTable(conn, "SPECIALTIES");
            dropTable(conn, "CATEGORIES");
            dropTable(conn, "REFERRALS");
            dropTable(conn, "ROLES");

            // Drop old tables if they exist (cleanup legacy)
            dropTable(conn, "FULL_TIME_DESIGNERS");
            dropTable(conn, "PART_TIME_DESIGNERS");
            dropTable(conn, "BOOKING_DESIGNERS");
            dropTable(conn, "ADMINS");


            // 2. CREATE TABLES

            // ROLES
            executeSQL(conn, "CREATE TABLE ROLES (RoleID INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, RoleName VARCHAR2(50) NOT NULL UNIQUE, Description VARCHAR2(255))");

            // REFERRALS
            executeSQL(conn, "CREATE TABLE REFERRALS (ReferralID INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, ReferralSource VARCHAR2(100) NOT NULL UNIQUE, Description VARCHAR2(255))");

            // SPECIALTIES
            executeSQL(conn, "CREATE TABLE SPECIALTIES (SpecialtyID INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, SpecialtyName VARCHAR2(100) NOT NULL UNIQUE, Description VARCHAR2(255))");

            // CATEGORIES (Design Styles)
            executeSQL(conn, "CREATE TABLE CATEGORIES (CategoryID INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, CategoryName VARCHAR2(100) NOT NULL UNIQUE, Description VARCHAR2(255))");

            // USERS
            executeSQL(conn, "CREATE TABLE USERS (" +
                    "UserID INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, " +
                    "Email VARCHAR2(100) NOT NULL UNIQUE, " +
                    "PasswordHash VARCHAR2(255) NOT NULL, " +
                    "FirstName VARCHAR2(50) NOT NULL, " +
                    "LastName VARCHAR2(50) NOT NULL, " +
                    "Phone VARCHAR2(20), " +
                    "Address VARCHAR2(255), " +
                    "RoleID INT NOT NULL, " +
                    "ReferralID INT, " +
                    "ReferredByUserID INT, " +
                    "CreatedAt TIMESTAMP DEFAULT CURRENT_TIMESTAMP, " +
                    "LastLogin TIMESTAMP, " +
                    "IsActive CHAR(1) DEFAULT '1' CHECK (IsActive IN ('0', '1')), " +
                    "CONSTRAINT FK_Users_Role FOREIGN KEY (RoleID) REFERENCES ROLES(RoleID), " +
                    "CONSTRAINT FK_Users_Referral FOREIGN KEY (ReferralID) REFERENCES REFERRALS(ReferralID), " +
                    "CONSTRAINT FK_Users_ReferredBy FOREIGN KEY (ReferredByUserID) REFERENCES USERS(UserID))");

            // STAFF
            executeSQL(conn, "CREATE TABLE STAFF (" +
                    "StaffID INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, " +
                    "UserID INT NOT NULL UNIQUE, " +
                    "StaffType VARCHAR2(20) NOT NULL CHECK (StaffType IN ('ADMIN', 'DESIGNER', 'MANAGER')), " +
                    "Department VARCHAR2(100), " +
                    "ManagerID INT, " +
                    "JoinDate DATE DEFAULT CURRENT_DATE, " +
                    "EndDate DATE, " +
                    "Salary DECIMAL(10, 2), " +
                    "CONSTRAINT FK_Staff_User FOREIGN KEY (UserID) REFERENCES USERS(UserID) ON DELETE CASCADE, " +
                    "CONSTRAINT FK_Staff_Manager FOREIGN KEY (ManagerID) REFERENCES STAFF(StaffID))");

            // DESIGNERS (Consolidated)
            executeSQL(conn, "CREATE TABLE DESIGNERS (" +
                    "DesignerID INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, " +
                    "StaffID INT NOT NULL UNIQUE, " +
                    "Bio CLOB, " +
                    "PrimarySpecialty VARCHAR2(100), " +
                    "PortfolioURL VARCHAR2(255), " +
                    "Status VARCHAR2(20) DEFAULT 'Active' CHECK (Status IN ('Active', 'On Leave', 'Inactive')), " +
                    "EmploymentType VARCHAR2(20) DEFAULT 'FULL_TIME' CHECK (EmploymentType IN ('FULL_TIME', 'PART_TIME', 'CONTRACT')), " +
                    "MaxHoursPerWeek INT DEFAULT 40, " +
                    "MinHoursGuaranteed INT DEFAULT 0, " +
                    "MaxSimultaneousProjects INT DEFAULT 5, " +
                    "MaxBookingsPerWeek INT DEFAULT 20, " +
                    "FlexibleSchedule CHAR(1) DEFAULT '0' CHECK (FlexibleSchedule IN ('0', '1')), " +
                    "AvailableHours VARCHAR2(500), " +
                    "TotalProjectsCompleted INT DEFAULT 0, " +
                    "AverageRating DECIMAL(3, 2), " +
                    "YearsExperience INT, " +
                    "CONSTRAINT FK_Designer_Staff FOREIGN KEY (StaffID) REFERENCES STAFF(StaffID) ON DELETE CASCADE)");

            // DESIGNER_SCHEDULE (New)
            executeSQL(conn, "CREATE TABLE DESIGNER_SCHEDULE (" +
                    "ScheduleID INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, " +
                    "DesignerID INT NOT NULL, " +
                    "AvailableDate DATE NOT NULL, " +
                    "StartTime VARCHAR2(5) DEFAULT '09:00', " +
                    "EndTime VARCHAR2(5) DEFAULT '18:00', " +
                    "IsAvailable NUMBER(1) DEFAULT 1, " +
                    "CONSTRAINT FK_Schedule_Designer FOREIGN KEY (DesignerID) REFERENCES DESIGNERS(DesignerID) ON DELETE CASCADE, " +
                    "CONSTRAINT UQ_Designer_Date UNIQUE (DesignerID, AvailableDate))");

            // DESIGNER_SPECIALTIES (Bridge)
            executeSQL(conn, "CREATE TABLE DESIGNER_SPECIALTIES (" +
                    "DesignerID INT NOT NULL, " +
                    "SpecialtyID INT NOT NULL, " +
                    "ProficiencyLevel VARCHAR2(20) DEFAULT 'INTERMEDIATE' CHECK (ProficiencyLevel IN ('BEGINNER', 'INTERMEDIATE', 'EXPERT')), " +
                    "YearsExperience INT DEFAULT 0, " +
                    "PRIMARY KEY (DesignerID, SpecialtyID), " +
                    "CONSTRAINT FK_DS_Designer FOREIGN KEY (DesignerID) REFERENCES DESIGNERS(DesignerID) ON DELETE CASCADE, " +
                    "CONSTRAINT FK_DS_Specialty FOREIGN KEY (SpecialtyID) REFERENCES SPECIALTIES(SpecialtyID) ON DELETE CASCADE)");

            // BOOKINGS
            executeSQL(conn, "CREATE TABLE BOOKINGS (" +
                    "BookingID INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, " +
                    "CustomerID INT NOT NULL, " +
                    "DesignerID INT NOT NULL, " +
                    "BookingDate DATE NOT NULL, " +
                    "BookingTime VARCHAR2(10) NOT NULL, " +
                    "Duration INT DEFAULT 60, " +
                    "Status VARCHAR2(20) DEFAULT 'Pending' CHECK (Status IN ('Pending', 'Confirmed', 'Completed', 'Cancelled', 'No-Show')), " +
                    "ServiceType VARCHAR2(100), " +
                    "Notes CLOB, " +
                    "EstimatedCost DECIMAL(10, 2), " +
                    "ActualCost DECIMAL(10, 2), " +
                    "CreatedAt TIMESTAMP DEFAULT CURRENT_TIMESTAMP, " +
                    "UpdatedAt TIMESTAMP DEFAULT CURRENT_TIMESTAMP, " +
                    "CancelledAt TIMESTAMP, " +
                    "CancellationReason VARCHAR2(500), " +
                    "CONSTRAINT FK_Booking_Customer FOREIGN KEY (CustomerID) REFERENCES USERS(UserID) ON DELETE CASCADE, " +
                    "CONSTRAINT FK_Booking_Designer FOREIGN KEY (DesignerID) REFERENCES DESIGNERS(DesignerID) ON DELETE CASCADE, " +
                    "CONSTRAINT UQ_Booking_Slot UNIQUE (DesignerID, BookingDate, BookingTime))");

            // BOOKING_CATEGORIES
            executeSQL(conn, "CREATE TABLE BOOKING_CATEGORIES (" +
                    "BookingID INT NOT NULL, " +
                    "CategoryID INT NOT NULL, " +
                    "PRIMARY KEY (BookingID, CategoryID), " +
                    "CONSTRAINT FK_BC_Booking FOREIGN KEY (BookingID) REFERENCES BOOKINGS(BookingID) ON DELETE CASCADE, " +
                    "CONSTRAINT FK_BC_Category FOREIGN KEY (CategoryID) REFERENCES CATEGORIES(CategoryID) ON DELETE CASCADE)");

            // 3. SEED DATA

            // Roles
            executeSQL(conn, "INSERT INTO ROLES (RoleName, Description) VALUES ('ADMIN', 'System administrator')");
            executeSQL(conn, "INSERT INTO ROLES (RoleName, Description) VALUES ('DESIGNER', 'Interior designer')");
            executeSQL(conn, "INSERT INTO ROLES (RoleName, Description) VALUES ('CUSTOMER', 'Regular customer')");

            // Referrals
            executeSQL(conn, "INSERT INTO REFERRALS (ReferralSource) VALUES ('Website')");
            executeSQL(conn, "INSERT INTO REFERRALS (ReferralSource) VALUES ('Friend Referral')");

            // Admin User (admin123)
            executeSQL(conn, "INSERT INTO USERS (Email, PasswordHash, FirstName, LastName, RoleID) " +
                    "VALUES ('admin@dottstudio.com', 'mIeWUM/hqNr2FShXO50eg0AXxwo82/JZzEFbPmV25DY=', 'System', 'Administrator', " +
                    "(SELECT RoleID FROM ROLES WHERE RoleName = 'ADMIN'))");
            
            executeSQL(conn, "INSERT INTO STAFF (UserID, StaffType, Department) " +
                    "VALUES ((SELECT UserID FROM USERS WHERE Email = 'admin@dottstudio.com'), 'ADMIN', 'IT')");

            System.out.println(">>> DATABASE SETUP COMPLETE. Schema Synchronized.");

        } catch (SQLException e) {
            e.printStackTrace();
        }
    }

    private static void dropTable(Connection conn, String startName) {
        try {
            executeSQL(conn, "DROP TABLE " + startName + " CASCADE CONSTRAINTS");
            System.out.println("Dropped " + startName);
        } catch (SQLException ignored) {
        }
    }

    private static void executeSQL(Connection conn, String sql) throws SQLException {
        try (Statement stmt = conn.createStatement()) {
            stmt.execute(sql);
        }
    }
}
